{% set version = "2.6.0" %}

package:
  name: connexion
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/zalando/connexion/archive/{{ version }}.tar.gz
  sha256: 6f18a187a6b7110ace7af73bce67109204523d3e602cce9c1a0d553ed8d182bd

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - connexion = connexion.cli:main

requirements:
  build:
    - python >=3
    - setuptools
    - flake8

  run:
    - python >=3
    - clickclick >=1.2
    - jsonschema >=2.5.1
    - pyyaml >=5.1
    - requests >=2.9.1
    - six >=1.9
    - inflection >=0.3.1
    - flask >=1.0.4
    - openapi-spec-validator >=0.2.4

test:
  imports:
    - connexion
    - connexion.apis
    - connexion.apps
    - connexion.decorators

  commands:
    - connexion --version

about:
  home: https://github.com/zalando/connexion
  license: Apache-2.0
  summary: 'Swagger/OpenAPI First framework for Python on top of Flask with automatic endpoint validation & OAuth2 support'
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: https://github.com/zalando/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
